#!/usr/bin/env -S npx tsx
/**
 * agents-link — generate per-agent config from canonical .agents/ sources.
 *
 * Reads:
 *   .agents/mcp.json      — canonical MCP server registry
 *   .agents/skills/<n>/   — canonical skills (each has SKILL.md). Codex, Gemini,
 *                           Cursor (v2.4+), and OpenCode all read this directory
 *                           natively. Only Claude Code needs a symlink bridge.
 *
 * Writes (all gitignored — regenerate as needed):
 *   claude   → .claude/skills/<n>  per-skill symlinks → ../../.agents/skills/<n>
 *              (per-skill — not a dir-level symlink — so tool-only skills can
 *              coexist as real dirs in .claude/skills/)
 *              .mcp.json
 *   codex    → .codex/config.toml         (skills + AGENTS.md read natively)
 *   gemini   → .gemini/settings.json      (skills read natively; AGENTS.md aliased)
 *   cursor   → .cursor/mcp.json           (skills + AGENTS.md read natively)
 *   opencode → opencode.json mcp block    (skills + AGENTS.md read natively;
 *                                          other keys preserved)
 *
 * Safety:
 *   - JSON outputs MERGE with existing files — user keys outside our managed
 *     section are preserved. Managed sections are replaced wholesale.
 *   - Symlink targets refuse to clobber a real file or directory; pass --force
 *     to override.
 *   - Generated text files (codex TOML, cursor .mdc) carry a marker line; the
 *     linker refuses to overwrite a file lacking it unless --force is set.
 *   - --dry-run prints planned actions without writing.
 *
 * Usage:
 *   tsx scripts/agents-link.ts                      # all tools
 *   tsx scripts/agents-link.ts --tool=claude        # one tool
 *   tsx scripts/agents-link.ts --tool=claude,gemini # several
 *   tsx scripts/agents-link.ts --dry-run            # preview only
 *   tsx scripts/agents-link.ts --force              # override safety checks
 */
import { parseArgs } from "node:util";
import * as fs from "node:fs";
import * as path from "node:path";

const ROOT = process.cwd();
const AGENTS_DIR = path.join(ROOT, ".agents");
const MCP_JSON = path.join(AGENTS_DIR, "mcp.json");
const SKILLS_DIR = path.join(AGENTS_DIR, "skills");
const MARKER = "Generated by scripts/agents-link.ts";

type Server = {
  description?: string;
  command?: string;
  args?: string[];
  env?: Record<string, string>;
  url?: string;
  headers?: Record<string, string>;
  auth?: "none" | "oauth" | "bearer";
  bearerEnvVar?: string;
  targets?: Tool[];
};
type Registry = { servers: Record<string, Server> };
type Tool = "claude" | "codex" | "gemini" | "cursor" | "opencode";
const ALL_TOOLS: Tool[] = ["claude", "codex", "gemini", "cursor", "opencode"];

type Opts = { dryRun: boolean; force: boolean };

// ────────────────────────────────────────────────────────── shared

function loadRegistry(): Registry {
  if (!fs.existsSync(MCP_JSON)) {
    console.error(`error: ${MCP_JSON} not found`);
    process.exit(1);
  }
  const raw = JSON.parse(fs.readFileSync(MCP_JSON, "utf8"));
  return { servers: raw.servers ?? {} };
}

function listSkills(): string[] {
  if (!fs.existsSync(SKILLS_DIR)) return [];
  return fs
    .readdirSync(SKILLS_DIR, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .filter((d) => fs.existsSync(path.join(SKILLS_DIR, d.name, "SKILL.md")))
    .map((d) => d.name)
    .sort();
}

function serversFor(reg: Registry, tool: Tool): [string, Server][] {
  return Object.entries(reg.servers).filter(
    ([, s]) => !s.targets || s.targets.includes(tool),
  );
}

function isStdio(s: Server): boolean {
  return typeof s.command === "string";
}

function rel(p: string): string {
  return path.relative(ROOT, p) || p;
}

function ensureDir(p: string, opts: Opts): void {
  if (opts.dryRun) return;
  fs.mkdirSync(p, { recursive: true });
}

// Refuse to overwrite a non-managed text file unless --force.
function checkTextManaged(file: string, opts: Opts): "new" | "managed" | "blocked" {
  if (!fs.existsSync(file)) return "new";
  const existing = fs.readFileSync(file, "utf8");
  if (existing.includes(MARKER)) return "managed";
  if (opts.force) {
    console.warn(`  ⚠ ${rel(file)} lacks marker but --force set, overwriting`);
    return "managed";
  }
  console.error(
    `  ✗ refusing to overwrite ${rel(file)} (lacks "${MARKER}" marker). Use --force to override.`,
  );
  return "blocked";
}

function writeText(file: string, content: string, opts: Opts): boolean {
  ensureDir(path.dirname(file), opts);
  if (opts.dryRun) {
    console.log(`  [dry] would write ${rel(file)}`);
    return true;
  }
  fs.writeFileSync(file, content);
  console.log(`  wrote ${rel(file)}`);
  return true;
}

function readJsonOr<T extends Record<string, unknown>>(file: string, fallback: T): T {
  if (!fs.existsSync(file)) return fallback;
  try {
    return JSON.parse(fs.readFileSync(file, "utf8")) as T;
  } catch {
    console.warn(`  ⚠ ${rel(file)} unparseable, treating as empty`);
    return fallback;
  }
}

function writeJsonMerged(
  file: string,
  patch: Record<string, unknown>,
  opts: Opts,
): void {
  const existing = readJsonOr(file, {});
  const merged = { ...existing, ...patch };
  ensureDir(path.dirname(file), opts);
  const out = JSON.stringify(merged, null, 2) + "\n";
  if (opts.dryRun) {
    console.log(`  [dry] would merge ${rel(file)}`);
    return;
  }
  fs.writeFileSync(file, out);
  console.log(`  merged ${rel(file)}`);
}

// Replace symlink only. Refuse to clobber real file/dir without --force.
function safeSymlink(link: string, target: string, opts: Opts): boolean {
  let existed: "missing" | "symlink" | "file" | "dir" = "missing";
  try {
    const st = fs.lstatSync(link);
    if (st.isSymbolicLink()) existed = "symlink";
    else if (st.isDirectory()) existed = "dir";
    else existed = "file";
  } catch {
    /* missing */
  }

  if (existed === "file" || existed === "dir") {
    if (!opts.force) {
      console.error(
        `  ✗ refusing to replace real ${existed} at ${rel(link)} with symlink. Use --force to override.`,
      );
      return false;
    }
    console.warn(`  ⚠ replacing real ${existed} at ${rel(link)} (--force)`);
  }

  if (opts.dryRun) {
    console.log(`  [dry] would link ${rel(link)} → ${target}`);
    return true;
  }

  if (existed !== "missing") {
    if (existed === "symlink" || existed === "file") fs.unlinkSync(link);
    else fs.rmSync(link, { recursive: true, force: true });
  }
  fs.symlinkSync(target, link);
  console.log(`  link  ${rel(link)} → ${target}`);
  return true;
}

// ────────────────────────────────────────────────────────── claude

function linkClaude(reg: Registry, skills: string[], opts: Opts): void {
  console.log("→ claude");
  const skillsOut = path.join(ROOT, ".claude", "skills");

  // If .claude/skills is itself a symlink (legacy dir-level link), unlink so
  // we can put per-skill symlinks inside a real directory.
  try {
    const st = fs.lstatSync(skillsOut);
    if (st.isSymbolicLink()) {
      if (!opts.dryRun) fs.unlinkSync(skillsOut);
      console.log(`  unlink ${rel(skillsOut)} (was dir-level symlink)`);
    }
  } catch {
    /* missing */
  }

  ensureDir(skillsOut, opts);

  // Per-skill symlinks. Real dirs/files in .claude/skills/ that aren't in our
  // skills list (i.e. tool-only skills the user added) are left alone.
  for (const name of skills) {
    const link = path.join(skillsOut, name);
    const target = path.join("..", "..", ".agents", "skills", name);
    safeSymlink(link, target, opts);
  }

  // Sweep stale symlinks: any symlink in .claude/skills/ pointing at our
  // .agents/skills/ tree whose name no longer exists upstream gets removed.
  const skillSet = new Set(skills);
  if (fs.existsSync(skillsOut)) {
    for (const entry of fs.readdirSync(skillsOut, { withFileTypes: true })) {
      if (!entry.isSymbolicLink()) continue;
      if (skillSet.has(entry.name)) continue;
      const linkPath = path.join(skillsOut, entry.name);
      const target = fs.readlinkSync(linkPath);
      if (target.includes(path.join(".agents", "skills"))) {
        if (!opts.dryRun) fs.unlinkSync(linkPath);
        console.log(`  unlink ${rel(linkPath)} (orphaned — no longer in .agents/skills/)`);
      }
    }
  }

  const mcpServers: Record<string, unknown> = {};
  for (const [name, s] of serversFor(reg, "claude")) {
    if (isStdio(s)) {
      mcpServers[name] = {
        command: s.command,
        ...(s.args ? { args: s.args } : {}),
        ...(s.env ? { env: s.env } : {}),
      };
    } else {
      const entry: Record<string, unknown> = { type: "http", url: s.url };
      const headers: Record<string, string> = { ...(s.headers ?? {}) };
      if (s.auth === "bearer" && s.bearerEnvVar) {
        headers["Authorization"] = `Bearer \${${s.bearerEnvVar}}`;
      }
      if (Object.keys(headers).length) entry.headers = headers;
      mcpServers[name] = entry;
    }
  }
  writeJsonMerged(path.join(ROOT, ".mcp.json"), { mcpServers }, opts);
}

// ────────────────────────────────────────────────────────── codex

function tomlEscape(s: string): string {
  return `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

function tomlArray(arr: string[]): string {
  return `[${arr.map(tomlEscape).join(", ")}]`;
}

function tomlInlineTable(obj: Record<string, string>): string {
  const inner = Object.entries(obj)
    .map(([k, v]) => `${k} = ${tomlEscape(v)}`)
    .join(", ");
  return `{ ${inner} }`;
}

function linkCodex(reg: Registry, opts: Opts): void {
  console.log("→ codex");
  const file = path.join(ROOT, ".codex", "config.toml");
  if (checkTextManaged(file, opts) === "blocked") return;

  const lines: string[] = [
    `# ${MARKER}. Edit .agents/mcp.json then re-run.`,
    `# User-level Codex preferences belong in ~/.codex/config.toml.`,
    "",
  ];
  for (const [name, s] of serversFor(reg, "codex")) {
    lines.push(`[mcp_servers.${name}]`);
    if (isStdio(s)) {
      lines.push(`command = ${tomlEscape(s.command!)}`);
      if (s.args?.length) lines.push(`args = ${tomlArray(s.args)}`);
      if (s.env) lines.push(`env = ${tomlInlineTable(s.env)}`);
    } else {
      lines.push(`url = ${tomlEscape(s.url!)}`);
      if (s.auth === "bearer" && s.bearerEnvVar) {
        lines.push(`bearer_token_env_var = ${tomlEscape(s.bearerEnvVar)}`);
      }
      if (s.headers) lines.push(`http_headers = ${tomlInlineTable(s.headers)}`);
      // OAuth: no extra TOML needed; user runs `codex login mcp <name>`.
    }
    lines.push("");
  }
  writeText(file, lines.join("\n"), opts);
}

// ────────────────────────────────────────────────────────── gemini

function linkGemini(reg: Registry, opts: Opts): void {
  console.log("→ gemini");
  const mcpServers: Record<string, unknown> = {};
  for (const [name, s] of serversFor(reg, "gemini")) {
    if (name.includes("_")) {
      console.warn(`  ⚠ gemini: server name "${name}" contains "_" — rename to use "-".`);
    }
    if (isStdio(s)) {
      mcpServers[name] = {
        command: s.command,
        ...(s.args ? { args: s.args } : {}),
        ...(s.env ? { env: s.env } : {}),
      };
    } else {
      const entry: Record<string, unknown> = { httpUrl: s.url };
      const headers: Record<string, string> = { ...(s.headers ?? {}) };
      if (s.auth === "bearer" && s.bearerEnvVar) {
        headers["Authorization"] = `Bearer $${s.bearerEnvVar}`;
      }
      if (Object.keys(headers).length) entry.headers = headers;
      mcpServers[name] = entry;
    }
  }

  // Merge: keep existing context.fileName entries, ensure AGENTS.md and
  // GEMINI.md are first (deduped). Replace mcpServers wholesale.
  const file = path.join(ROOT, ".gemini", "settings.json");
  const existing = readJsonOr<Record<string, unknown>>(file, {});
  const existingCtx = (existing.context as Record<string, unknown> | undefined) ?? {};
  const existingFiles = Array.isArray(existingCtx.fileName)
    ? (existingCtx.fileName as string[])
    : [];
  const dedupedFiles = ["AGENTS.md", "GEMINI.md", ...existingFiles].filter(
    (v, i, a) => a.indexOf(v) === i,
  );

  writeJsonMerged(
    file,
    {
      mcpServers,
      context: { ...existingCtx, fileName: dedupedFiles },
    },
    opts,
  );
}

// ────────────────────────────────────────────────────────── cursor

// Cursor v2.4+ reads .agents/skills/ and AGENTS.md natively, so we only
// emit the MCP config.
function linkCursor(reg: Registry, opts: Opts): void {
  console.log("→ cursor");
  const mcpServers: Record<string, unknown> = {};
  for (const [name, s] of serversFor(reg, "cursor")) {
    if (isStdio(s)) {
      mcpServers[name] = {
        type: "stdio",
        command: s.command,
        ...(s.args ? { args: s.args } : {}),
        ...(s.env ? { env: s.env } : {}),
      };
    } else {
      const entry: Record<string, unknown> = { url: s.url };
      const headers: Record<string, string> = { ...(s.headers ?? {}) };
      if (s.auth === "bearer" && s.bearerEnvVar) {
        headers["Authorization"] = `Bearer \${env:${s.bearerEnvVar}}`;
      }
      if (Object.keys(headers).length) entry.headers = headers;
      mcpServers[name] = entry;
    }
  }
  writeJsonMerged(path.join(ROOT, ".cursor", "mcp.json"), { mcpServers }, opts);
}

// ────────────────────────────────────────────────────────── opencode

function linkOpencode(reg: Registry, opts: Opts): void {
  console.log("→ opencode");
  const file = path.join(ROOT, "opencode.json");

  const mcp: Record<string, unknown> = {};
  for (const [name, s] of serversFor(reg, "opencode")) {
    if (isStdio(s)) {
      mcp[name] = {
        type: "local",
        command: [s.command!, ...(s.args ?? [])],
        ...(s.env ? { environment: s.env } : {}),
        enabled: true,
      };
    } else {
      const entry: Record<string, unknown> = {
        type: "remote",
        url: s.url,
        enabled: true,
      };
      if (s.auth === "oauth") entry.oauth = {};
      if (s.auth === "bearer" && s.bearerEnvVar) {
        entry.headers = { Authorization: `Bearer {env:${s.bearerEnvVar}}` };
      }
      if (s.headers) entry.headers = { ...(entry.headers as object), ...s.headers };
      mcp[name] = entry;
    }
  }

  // Merge: preserve $schema, agent, instructions, etc.
  const existing = readJsonOr<Record<string, unknown>>(file, {});
  if (!existing.$schema) existing.$schema = "https://opencode.ai/config.json";
  writeJsonMerged(file, { ...existing, mcp }, opts);
}

// ────────────────────────────────────────────────────────── main

function main(): void {
  const { values } = parseArgs({
    options: {
      tool: { type: "string" },
      "dry-run": { type: "boolean" },
      force: { type: "boolean" },
      help: { type: "boolean", short: "h" },
    },
  });

  if (values.help) {
    console.log(`agents-link — generate per-agent config from .agents/

Usage:
  tsx scripts/agents-link.ts [--tool=claude,codex,gemini,cursor,opencode]
                             [--dry-run] [--force]

  --dry-run   print planned actions, write nothing
  --force     bypass safety checks (overwrite non-managed files / clobber dirs)

Reads .agents/mcp.json and .agents/skills/, writes per-tool configs.
JSON outputs merge with existing files (user keys preserved).
Codex TOML and Cursor .mdc files require an "${MARKER}" marker.`);
    return;
  }

  const opts: Opts = {
    dryRun: !!values["dry-run"],
    force: !!values.force,
  };

  const tools: Tool[] = values.tool
    ? (values.tool.split(",").map((t) => t.trim()) as Tool[])
    : ALL_TOOLS;
  for (const t of tools) {
    if (!ALL_TOOLS.includes(t)) {
      console.error(`unknown tool: ${t}. valid: ${ALL_TOOLS.join(", ")}`);
      process.exit(1);
    }
  }

  const reg = loadRegistry();
  const skills = listSkills();
  const banner = opts.dryRun ? " [DRY RUN]" : "";
  console.log(
    `linking ${Object.keys(reg.servers).length} mcp server(s) and ${skills.length} skill(s) → ${tools.join(", ")}${banner}\n`,
  );

  if (tools.includes("claude")) linkClaude(reg, skills, opts);
  if (tools.includes("codex")) linkCodex(reg, opts);
  if (tools.includes("gemini")) linkGemini(reg, opts);
  if (tools.includes("cursor")) linkCursor(reg, opts);
  if (tools.includes("opencode")) linkOpencode(reg, opts);

  console.log(opts.dryRun ? "\ndone (dry run — no files written)." : "\ndone.");
}

main();
